#!/bin/bash
#!/usr/bin/env bash
# Infinite loop script that handles SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
 #!/usr/bin/env bash
# Script to send SIGTERM to 7-highlander process

pkill -f 7-highlander
