#!/bin/bash
#!/usr/bin/env bash
# Runs indefinitely and handles SIGTERM gracefully
# Trap SIGTERM and print a custom message instead of exiting
trap 'echo
# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
