#!/bin/bash
#!/usr/bin/env bash
# Trap SIGTERM and print a custom message instead of exiting
trap 'echo "I am invincible!!!"' SIGTERM
# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
