#!/bin/bash
 #!/usr/bin/env bash
# Forcefully kills the 7-highlander process using SIGKILL
# Find the PID(s) of the 7-highlander process
pid=$(pgrep -f 7-highlander)
# If the process is running, send SIGKILL
if [ -n "$pid" ]; then
  kill -9 "$pid"
  echo "Beheaded 7-highlander process with PID(s): $pid"
else
  echo "No 7-highlander process found."
fi
